USE [ONIPVC]
GO

IF COL_LENGTH('dbo.FORMACAO', 'ativo') IS NULL
BEGIN
    ALTER TABLE [dbo].[FORMACAO]
    ADD [ativo] BIT NOT NULL
        CONSTRAINT [DF__FORMACAO__ativo__628FA482] DEFAULT ((1));
END
GO
